const $=s=>document.querySelector(s),api=()=>window.pywebview.api;
const ui={modal:$("#modal"),fileModal:$("#file-modal"),form:$("#form"),fields:$("#fields"),list:$("#list"),empty:$("#empty"),notice:$("#notice"),error:$("#form-error"),create:$("#create")};
const fileLabels={exclude:"exclude",iexclude:"iexclude",file_from:"file-from",exclude_larger_than:"exclude-larger-than"};
let repositories=[],policies=[],forgetPolicies=[],selected=null,editingFiles=null,editingFileKey=null;
function fail(t,m){t.textContent=m;t.hidden=false}function clear(){ui.notice.hidden=true;ui.list.className="grid";ui.list.replaceChildren()}function close(){ui.modal.hidden=true}function closeFile(){ui.fileModal.hidden=true;editingFileKey=null}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function field(id,label,type="text",value="",extra=""){return `<label>${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function open(title,html,submit,wide=false){$("#modal-title").textContent=title;ui.fields.innerHTML=html;ui.error.hidden=true;ui.form.classList.toggle("log-dialog",wide);ui.modal.hidden=false;ui.form.onsubmit=submit}
function setup(title,intro,button,handler){clear();$("#title").textContent=title;$("#intro").textContent=intro;ui.create.textContent=button||"";ui.create.hidden=!button;ui.create.onclick=handler||null}
function card(title,subtitle,buttons){const el=document.createElement("article");el.className="card";el.innerHTML='<div class="symbol">R</div><h2></h2><p></p><div class="card-actions"></div>';el.querySelector("h2").textContent=title;el.querySelector("p").textContent=subtitle;for(const [label,fn,danger] of buttons){const b=document.createElement("button");b.className=danger?"danger":"secondary";b.textContent=label;b.onclick=fn;el.querySelector(".card-actions").append(b)}return el}
function show(items){ui.list.replaceChildren(...items);ui.empty.hidden=!!items.length}
function snapshotTable(snapshots){
  if(!snapshots.length)return show([]);
  const wrapper=document.createElement("div");wrapper.className="snapshot-table-wrap";
  const table=document.createElement("table");table.className="snapshot-table";
  table.innerHTML='<thead><tr><th>ID</th><th>시간</th><th>태그</th><th>경로</th><th><span class="sr-only">작업</span></th></tr></thead>';
  const body=document.createElement("tbody");
  for(const snapshot of snapshots){
    const row=document.createElement("tr");
    const values=[snapshot.id,snapshot.time,(snapshot.tags||[]).join(", ")||"—",(snapshot.paths||[]).join("\n")||"—"];
    values.forEach((value,index)=>{const cell=document.createElement("td");cell.textContent=value||"—";if(index===0)cell.className="snapshot-id";if(index===3)cell.className="snapshot-paths";row.append(cell)});
    const action=document.createElement("td");action.className="snapshot-action";
    const button=document.createElement("button");button.className="secondary";button.textContent="내용물 출력";button.onclick=()=>saveSnapshot(snapshot);
    action.append(button);row.append(action);body.append(row);
  }
  table.append(body);wrapper.append(table);ui.list.className="snapshot-list";ui.list.replaceChildren(wrapper);ui.empty.hidden=true;
}
async function loadRepositories(){setup("저장소","백업을 보관할 restic 저장소를 관리합니다.","＋ 저장소 등록",createRepository);const r=await api().list_repositories();if(!r.ok)return fail(ui.notice,r.error.message);repositories=r.data.repositories;show(repositories.map(repo=>card(repo.name,repo.directory,[["스냅샷",()=>loadSnapshots(repo)],["삭제",()=>deleteRepository(repo),true]])))}
function createRepository(){open("저장소 등록",field("name","이름 (영문·숫자)")+'<label>저장 경로</label><div class="path"><input id="directory" readonly required><button id="pick" type="button" class="secondary">폴더 선택</button></div>'+field("password","비밀번호","password"),async e=>{e.preventDefault();const r=await api().create_repository($("#name").value,$("#directory").value,$("#password").value);if(!r.ok)return fail(ui.error,r.error.message);close();loadRepositories()});$("#pick").onclick=async()=>{const r=await api().select_directory();if(r.ok&&r.data.directory)$("#directory").value=r.data.directory}}
function deleteRepository(repo){open("저장소 삭제",`<p>삭제 시 실제 저장소와 키도 삭제됩니다.<br><b>${esc(repo.directory)}</b></p>`+field("confirm","저장소 경로"),async e=>{e.preventDefault();const r=await api().delete_repository(repo.id,$("#confirm").value);if(!r.ok)return fail(ui.error,r.error.message);close();loadRepositories()})}
async function chooseRepository(next){if(!repositories.length){const r=await api().list_repositories();if(r.ok)repositories=r.data.repositories}open("저장소 선택",`<label>저장소<select id="repository-select">${repositories.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join("")}</select></label>`,e=>{e.preventDefault();const repo=repositories.find(r=>r.id===Number($("#repository-select").value));close();if(repo)next(repo)})}
async function loadPolicies(repo=null){if(!repo)return chooseRepository(loadPolicies);selected=repo;setup(`${repo.name} · 백업 정책`,"정책 저장 시 Windows 실행 스크립트가 생성됩니다.","＋ 정책 생성",()=>editPolicy());const [r,f]=await Promise.all([api().list_backup_policies(repo.id),api().list_forget_policies()]);if(!r.ok)return fail(ui.notice,r.error.message);policies=r.data.policies;forgetPolicies=f.ok?f.data.policies:[];show(policies.map(p=>card(p.name,p.backup_path,[["수정",()=>editPolicy(p)],["스크립트 갱신",()=>regenerate(p)],["삭제",()=>deletePolicy(p),true]])))}
function fileRows(){return '<div class="file-fields">'+Object.entries(fileLabels).map(([key,label])=>`<div class="file-field"><span>${label}</span><small id="${key}-status">${editingFiles[key].trim()?"입력됨":"비어 있음"}</small><button type="button" class="secondary file-edit" data-file-key="${key}">편집</button></div>`).join("")+'</div>'}
function openFileEditor(key){editingFileKey=key;const name=$("#policy-name").value.trim()||"<정책 이름>";$("#file-modal-title").textContent=`${fileLabels[key]} 편집`;$("#file-path").textContent=`./data/${key}/${name}.dat`;$("#file-content").value=editingFiles[key];ui.fileModal.hidden=false;$("#file-content").focus()}
async function editPolicy(policy=null){editingFiles={exclude:"",iexclude:"",file_from:"",exclude_larger_than:""};if(policy){const r=await api().get_policy_files(policy.id);if(r.ok)editingFiles=r.data.files}const options='<option value="">사용 안 함</option>'+forgetPolicies.map(f=>`<option value="${f.id}" ${f.id===policy?.forget_policy_id?'selected':''}>${esc(f.name)}</option>`).join("");const html=field("policy-name","이름 (영문·숫자)","text",policy?.name||"","required")+'<label>백업 경로</label><div class="path path-pickers"><input id="backup-path" readonly required value="'+esc(policy?.backup_path||"")+'"><button id="pick-backup" type="button" class="secondary">폴더</button><button id="pick-backup-file" type="button" class="secondary">파일</button></div>'+`<label>Forget 정책<select id="forget-policy">${options}</select></label>`+fileRows();open(policy?"백업 정책 수정":"백업 정책 생성",html,async e=>{e.preventDefault();const r=await api().save_backup_policy(selected.id,$("#policy-name").value,$("#backup-path").value,editingFiles,$("#forget-policy").value||null,policy?.id??null);if(!r.ok)return fail(ui.error,r.error.message);close();loadPolicies(selected)});$("#pick-backup").onclick=async()=>{const r=await api().select_backup_path();if(r.ok&&r.data.path)$("#backup-path").value=r.data.path};$("#pick-backup-file").onclick=async()=>{const r=await api().select_backup_file();if(r.ok&&r.data.path)$("#backup-path").value=r.data.path};document.querySelectorAll(".file-edit").forEach(b=>b.onclick=()=>openFileEditor(b.dataset.fileKey))}
async function regenerate(p){const r=await api().regenerate_backup_script(p.id);if(!r.ok)fail(ui.notice,r.error.message);else alert("스크립트를 갱신했습니다.")}
function deletePolicy(p){open("백업 정책 삭제",`<p>정책 이름 <b>${esc(p.name)}</b>을 정확히 입력하세요.</p>`+field("confirm","정책 이름"),async e=>{e.preventDefault();const r=await api().delete_backup_policy(p.id,$("#confirm").value);if(!r.ok)return fail(ui.error,r.error.message);close();loadPolicies(selected)})}
async function loadForgetPolicies(){setup("Forget 정책","restic forget 보존 정책을 독립적으로 관리합니다.","＋ 정책 생성",()=>editForget());const r=await api().list_forget_policies();if(!r.ok)return fail(ui.notice,r.error.message);forgetPolicies=r.data.policies;show(forgetPolicies.map(p=>card(p.name,p.auto_prune?"auto-prune 사용":"auto-prune 사용 안 함",[["수정",()=>editForget(p)],["삭제",()=>deleteForget(p),true]])))}
function editForget(policy=null){let html=field("forget-name","이름 (영문·숫자)","text",policy?.name||"","required");for(const k of ["keep_daily","keep_weekly","keep_monthly","keep_yearly","keep_last"])html+=field(k,k.replaceAll("_","-"),"number",policy?.[k]||"","min=1");for(const k of ["keep_within_daily","keep_within_weekly","keep_within_monthly","keep_within_yearly"])html+=field(k,k.replaceAll("_","-"),"text",policy?.[k]||"");html+=`<label class="check"><input id="auto_prune" type="checkbox" ${policy?.auto_prune?'checked':''}> auto-prune</label>`;open(policy?"Forget 정책 수정":"Forget 정책 생성",html,async e=>{e.preventDefault();const values={auto_prune:$("#auto_prune").checked};for(const k of ["keep_daily","keep_weekly","keep_monthly","keep_yearly","keep_last","keep_within_daily","keep_within_weekly","keep_within_monthly","keep_within_yearly"])values[k]=$("#"+k).value;const r=await api().save_forget_policy($("#forget-name").value,values,policy?.id??null);if(!r.ok)return fail(ui.error,r.error.message);close();await loadForgetPolicies();if(policy)alert(r.data.warning)})}
function deleteForget(p){open("Forget 정책 삭제",`<p>정책 이름 <b>${esc(p.name)}</b>을 정확히 입력하세요.</p>`+field("confirm","정책 이름"),async e=>{e.preventDefault();const r=await api().delete_forget_policy(p.id,$("#confirm").value);if(!r.ok)return fail(ui.error,r.error.message);close();loadForgetPolicies()})}
async function loadSnapshots(repo){selected=repo;setup(`${repo.name} · 스냅샷`,"스냅샷의 ID, 시간, 태그와 경로를 확인합니다.","",null);const r=await api().list_snapshots(repo.id);if(!r.ok)return fail(ui.notice,r.error.message);snapshotTable(r.data.snapshots)}
async function saveSnapshot(snapshot){const r=await api().save_snapshot_contents(selected.id,snapshot.snapshot_id||snapshot.id);if(!r.ok)return fail(ui.notice,r.error.message);if(!r.data.cancelled)alert(`저장했습니다: ${r.data.path}`)}
async function loadLogs(){setup("Logs","restic 작업의 날짜별 로그를 확인하고 정리합니다.","전체 삭제",deleteAllLogs);const r=await api().list_logs();if(!r.ok)return fail(ui.notice,r.error.message);show(r.data.logs.map(log=>card(log.name,`${log.size.toLocaleString()} bytes`,[["보기",()=>viewLog(log)],["삭제",()=>deleteLog(log),true]])))}
async function viewLog(log){const r=await api().read_log(log.name);if(!r.ok)return fail(ui.notice,r.error.message);open(log.name,`<label>로그 내용</label><textarea class="log-view" readonly>${esc(r.data.content)}</textarea>`,e=>{e.preventDefault();close()},true)}
async function deleteLog(log){if(!confirm(`${log.name} 로그를 삭제할까요?`))return;const r=await api().delete_log(log.name);if(!r.ok)return fail(ui.notice,r.error.message);loadLogs()}
async function deleteAllLogs(){if(!confirm("모든 로그를 삭제할까요?"))return;const r=await api().delete_all_logs();if(!r.ok)return fail(ui.notice,r.error.message);loadLogs()}
async function loadConfiguration(){setup("Configuration","Windows 작업 스케줄러의 자동 백업 설정을 관리합니다.","",null);const r=await api().get_configuration();if(!r.ok)return fail(ui.notice,r.error.message);const c=r.data.configuration;const form=document.createElement("form");form.className="settings card";form.innerHTML=`<label class="check"><input id="auto-enabled" type="checkbox" ${c.enabled?'checked':''}> 백업 자동 실행</label><fieldset id="auto-options"><label class="check"><input id="at-startup" type="checkbox" ${c.run_at_startup?'checked':''}> Windows 시작 시 실행</label>${field("interval-days","자동 실행 주기 (일)","number",c.interval_days,"min=1")}<label class="check"><input id="when-idle" type="checkbox" ${c.run_when_idle?'checked':''}> 컴퓨터가 유휴 상태일 때 실행</label></fieldset><div class="actions"><button class="primary">설정 저장</button></div>`;ui.list.className="settings-wrap";ui.list.replaceChildren(form);ui.empty.hidden=true;const toggle=()=>form.querySelector("fieldset").disabled=!$("#auto-enabled").checked;$("#auto-enabled").onchange=toggle;toggle();form.onsubmit=async e=>{e.preventDefault();const result=await api().save_configuration({enabled:$("#auto-enabled").checked,run_at_startup:$("#at-startup").checked,interval_days:$("#interval-days").value,run_when_idle:$("#when-idle").checked});if(!result.ok)return fail(ui.notice,result.error.message);alert("설정을 저장했습니다.")}}
function formatBytes(value){let size=Number(value)||0;const units=["B","KB","MB","GB","TB"];let unit=0;while(size>=1024&&unit<units.length-1){size/=1024;unit++}return `${size.toFixed(unit?1:0)} ${units[unit]}`}
async function manualBackup(button){const modal=$("#progress-modal"),dialog=modal.querySelector(".dialog"),title=$("#progress-title"),message=$("#progress-message"),closeButton=$("#progress-close"),bar=modal.querySelector(".progress-bar"),percent=$("#progress-percent"),detail=$("#progress-detail"),file=$("#progress-file");button.disabled=true;dialog.className="dialog progress-dialog";title.textContent="백업을 실행하고 있습니다";message.textContent="restic에서 백업할 파일을 확인하고 있습니다.";percent.textContent="0%";detail.textContent="준비 중…";file.textContent="";bar.style.width="0%";closeButton.hidden=true;modal.hidden=false;try{const started=await api().start_manual_backup();if(!started.ok)throw new Error(started.error.message);while(true){await new Promise(resolve=>setTimeout(resolve,500));const result=await api().get_manual_backup_status();if(!result.ok)throw new Error(result.error.message);const state=result.data.backup,pct=Math.max(0,Math.min(100,Math.round((state.percent||0)*100)));bar.style.width=`${pct}%`;percent.textContent=`${pct}%`;detail.textContent=state.total_files?`${state.files_done.toLocaleString()} / ${state.total_files.toLocaleString()}개 파일 · ${formatBytes(state.bytes_done)} / ${formatBytes(state.total_bytes)}`:`${formatBytes(state.bytes_done)} 처리됨`;file.textContent=(state.current_files||[]).join(" · ");if(state.running)continue;if(state.status==="failed")throw new Error(state.error||"백업에 실패했습니다.");dialog.classList.add("done");title.textContent="백업을 완료했습니다";message.textContent="모든 백업 스크립트가 정상적으로 완료되었습니다.";percent.textContent="100%";bar.style.width="100%";closeButton.hidden=false;break}}catch(error){dialog.classList.add("failed");title.textContent="백업에 실패했습니다";message.textContent=error.message||"수동 백업을 실행하지 못했습니다.";closeButton.hidden=false}finally{button.disabled=false}}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=close);document.querySelectorAll("[data-file-close]").forEach(x=>x.onclick=closeFile);$("#progress-close").onclick=()=>$("#progress-modal").hidden=true;$("#save-file-content").onclick=()=>{editingFiles[editingFileKey]=$("#file-content").value;$("#"+editingFileKey+"-status").textContent=editingFiles[editingFileKey].trim()?"입력됨":"비어 있음";closeFile()};
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>({repositories:loadRepositories,policies:()=>loadPolicies(),forget:loadForgetPolicies,logs:loadLogs,config:loadConfiguration,manual:()=>manualBackup(b)}[b.dataset.page]()));window.addEventListener("pywebviewready",loadRepositories);
